name: C/C++ CI
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - docs/**
      - bin/**
  pull_request:
    paths-ignore:
      - docs/**
      - bin/**
jobs:
  build_linux:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: prerequisites
        run: sudo apt -qq update && sudo apt -yqq install libusb-1.0-0-dev
      - name: cmake_make
        run: mkdir build && cmake -S . -B build && cd build && make
      - name: compress
        run: |
          tar zcvf librtlsdr_build_${{ matrix.os }}.tar.gz \
          --directory=build/src \
          --exclude=CMakeFiles \
          --exclude=*.cmake \
          --exclude=Makefile \
          --exclude=rtl_app_ver.h .
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.os }}_latest_build
          path: librtlsdr_build_${{ matrix.os }}.tar.gz
          
  build_macos:
    strategy:
      matrix:
        os:
          - macos-latest
          - macos-15-intel
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: cmake_make
        run: mkdir build && cmake -S . -B build && cd build && make
      - name: compress
        run: |
          tar zcvf librtlsdr_build_${{ matrix.os }}.tar.gz --directory=build/src \
          --exclude=CMakeFiles --exclude=*.cmake --exclude=Makefile \
          --exclude=rtl_app_ver.h .
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.os }}_latest_build
          path: librtlsdr_build_${{ matrix.os }}.tar.gz
        
  cross_build_win32_win64_latest:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      THREADS_USE_PTHREADS_WIN32: true
      CMAKE_FIND_DEBUG_MODE: TRUE
    steps:
      - uses: actions/checkout@v6
      - name: prerequisites
        run: |
          sudo apt -qq update && sudo apt -yqq install gcc-mingw-w64 \
          mingw-w64-i686-dev mingw-w64-x86-64-dev mingw-w64-tools \
          mingw-w64-common libpthread-stubs0-dev libusb-dev libusb-1.0-0-dev \
          mingw64-gcc mingw64-binutils mingw64-libusbx
          sudo find / -name '*pthread*'
          sudo find / -name 'libusb*' 
      - name: cmake_make
        run: mkdir build && cd build && mingw-w64-cmake .. && mingw-w64-make install
